# Generated by Django 4.2 on 2024-05-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='image',
            field=models.ImageField(blank=True, default='suppliers/person.png', null=True, upload_to='suppliers/'),
        ),
    ]
