# Generated by Django 4.2 on 2024-05-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_supplier_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Brand'),
        ),
    ]
