# Generated by Django 4.2 on 2024-05-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_brand_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/product.png', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='image',
            field=models.ImageField(blank=True, default='suppliers/persona1.svg', null=True, upload_to='suppliers/'),
        ),
    ]
